
/**funciones de botones-navegation */

function openDownload(){
    
    window.location.href=("https://www.tibia.com/account/?subtopic=downloadclient");

     
}

function openMore(){
    
    window.open("https://www.tibia.com/news/?subtopic=latestnews");

}


function openSpells(){
    
    window.location.href=("https://www.tibia.com/library/?subtopic=spells");

}

function openListMoster(){
    
    window.location.href=("https://www.tibia.com/library/?subtopic=creatures");

}

function openListplayer(){
    
    window.location.href=("https://www.tibia.com/community/?subtopic=worlds");

}

function openAccunt(){
    
    window.location.href=("https://www.tibia.com/account/?subtopic=createaccount");

}

function openSupport(){
    
    window.location.href=("https://www.tibia.com/support/?subtopic=tibiarules");

}

function openReadmore(){
    
    window.location.href=("https://www.tibia.com/news/?subtopic=latestnews");

}
/**botones de cards */
function openMoreMons(){
    
    window.location.href=("https://www.tibia.com/library/?subtopic=creatures&race=demon");

}

function openMorequest(){
    
    window.location.href=("https://www.tibia.com/library/?subtopic=worldquests");

}

function openMoreGremios(){
    
    window.location.href=("https://www.tibia.com/community/?subtopic=guilds&page=view");

}

function openMoreCiudad(){
    
    window.location.href=("https://www.tibia.com/community/?subtopic=houses");

}
/**socialmedia */

function openface(){
    
    window.open("https://www.facebook.com/javier.torresviloria/");

}

function openGithub(){
    
    window.open("https://github.com/yulien-prom/");

}

function openlikedin(){
    
    window.open("https://www.linkedin.com/in/yulio-torres-21931120a/");

}

/**Scroll reveal */
ScrollReveal().reveal('.showcase',{delay: 800});
ScrollReveal().reveal('.news-cards', {delay:900});
ScrollReveal().reveal('.cards-banner-one', {delay:1000});


